name: Release Docker Image

on:
  push:
    branches:
      - 'releases/**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        # Get a copy of the repository
        uses: actions/checkout@v3 
      - 
        # Set up virtualization platform to support building for more platforms
        name: Set up QEMU 
        uses: docker/setup-qemu-action@v2
      - 
        # Set up the docker build toolchain
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        # Retrieve the version number from the git tag/git event
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            bonajo/prj2-db-example
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - 
        # Login to Docker Hub, using the secrets stored in the repository
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        # Build the Docker image, and set the metadata from previous step
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        # Push the Docker image to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}